In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


### Creating Tensor

In [ ]:
# Using numpy
a = torch.empty(2,3)
## Memory allocate in the memory
## not assign the value
a

tensor([[-9.9835e-30,  4.5786e-41, -9.9835e-30],
        [ 4.5786e-41,  2.1707e-18,  1.9284e+31]])

In [ ]:
# Type
type(a)

torch.Tensor

In [ ]:
# Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# rand
torch.rand(2,3)

tensor([[0.9713, 0.7015, 0.1729],
        [0.0889, 0.6707, 0.5120]])

In [ ]:
# rand
torch.rand(2,3)

tensor([[0.6359, 0.0352, 0.8858],
        [0.6678, 0.4949, 0.2390]])

In [ ]:
## use of the seed
## Each time rand output is same
torch.manual_seed(100)
torch.rand(2,3)



tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Torch tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Other ways
print("Using Arange  : \n",torch.arange(0,18,2).reshape(3,3))
print("Using Arange  :\n",torch.arange(0,18,2))

# Using linspace
print("Using Linspace : \n",torch.linspace(0,10,10))

# Identity Metrix
print("Identity Metrix : \n",torch.eye(3))

# Full Matrix
print("Full Metrix : \n",torch.full((3,3),5))



Using Arange  : 
 tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])
Using Arange  :
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])
Using Linspace : 
 tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Identity Metrix : 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Full Metrix : 
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

## Here copy the shape of the another tensor



tensor([[0, 0, 0],
        [0, 1, 0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

# In the x all the vales are int
# In the rand function values return in the float value so here shows the error

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
# so we explicity change the data type


## Tensor Datatype

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# Using to ()

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [ ]:
# Addition
print(x+2)

# sub
print(x-2)

# multiplication
print(x*2)

# division
print(x/3)

# int division
(x*100)//3

# Mode
((x*100)//3)*2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
tensor([[0.0746, 0.1008],
        [0.0595, 0.2746]])


tensor([[14., 20.],
        [10., 54.]])

## Element Wise Tensor

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a,b

(tensor([[0.5557, 0.9770, 0.4440],
         [0.9478, 0.7445, 0.4892]]),
 tensor([[0.2426, 0.7003, 0.5277],
         [0.2472, 0.7909, 0.4235]]))

In [ ]:
# Add
print(a+b)

# sub
print(a-b)

# mul
print(a*b)

# div
print(a/b)

# Power
print(a**b)

# Modulo
print(a%b)

# Floor Division
print(a//b)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])
tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])
tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])
tensor([[2., 1., 0.],
        [3., 0., 1.]])


In [ ]:
c = torch.tensor([1,-2.5,3,4,-2,3.9,2.3])

# abs
print(torch.abs(c))

# Negative
print(torch.neg(c))

# Square
print(torch.square(c))

# sqrt
print(torch.round(c))

# Ceil
print(torch.ceil(c))

# floor
print(torch.floor(c))

# clamp
torch.clamp(c,min=-1,max=3)

## Redution Operation

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [ ]:
# sum
print(torch.sum(e))
# columns sum
print(torch.sum(e,dim=0))
# rows sum
print(torch.sum(e,dim=1))

# mean
print(torch.mean(e))
# columns
print(torch.mean(e,dim=0))
# max and min
print(torch.max(e))
print(torch.min(e))
# standard
print(torch.std(e))
# variance
print(torch.var(e))

# argmax
print(torch.argmax(e)) # position of the largest value
# argmin
print(torch.argmin(e)) # position of the lowert value

## Matrix multiplication
print(torch.matmul(e,e.T))





tensor(42.)
tensor([14., 16., 12.])
tensor([17., 25.])
tensor(7.)
tensor([7., 8., 6.])
tensor(9.)
tensor(5.)
tensor(1.7889)
tensor(3.2000)
tensor(3)
tensor(0)
tensor([[ 99., 143.],
        [143., 211.]])


In [ ]:
# dot product
vt1  =  torch.tensor([1,2,3])
vt2 = torch.tensor([3,4,5])
print(torch.dot(vt1,vt2))

# transpose
print(torch.transpose(e,0,1))

# determinat
e1 = torch.rand(3,3)
print(torch.det(e1))

# inverse
print(torch.inverse(e1))

tensor(26)
tensor([[5., 9.],
        [7., 9.],
        [5., 7.]])
tensor(-0.1209)
tensor([[-4.9385,  3.5159,  0.8150],
        [ 5.2228, -2.1719, -1.3709],
        [ 0.3510, -1.2112,  1.3416]])


## Comparsion Operator

In [ ]:
i = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)


tensor([[7., 2., 3.],
        [8., 5., 6.]])
tensor([[2, 9, 5],
        [0, 4, 2]])


In [ ]:
# grater than
print(i>j)

# less then
print(i<j)

# euqal to
print(i==j)

# not equal to
print(i!=j)

tensor([[ True, False, False],
        [ True,  True,  True]])
tensor([[False,  True,  True],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


In [ ]:
k = torch.randint(size=(2,3),low=0,high=10)
k

tensor([[1, 1, 2],
        [4, 7, 2]])

In [ ]:
# log
print(torch.log(k))

# exp
print(torch.exp(k))

# sqrt
print(torch.sqrt(k))

# sigmoid
print(torch.sigmoid(k))

# relu
print(torch.relu(k))


tensor([[0.0000, 0.0000, 0.6931],
        [1.3863, 1.9459, 0.6931]])
tensor([[   2.7183,    2.7183,    7.3891],
        [  54.5981, 1096.6332,    7.3891]])
tensor([[1.0000, 1.0000, 1.4142],
        [2.0000, 2.6458, 1.4142]])
tensor([[0.7311, 0.7311, 0.8808],
        [0.9820, 0.9991, 0.8808]])
tensor([[1, 1, 2],
        [4, 7, 2]])


## Inplace Operation


In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

m+n

tensor([[0.2732, 0.3397, 0.1879],
        [0.5534, 0.2682, 0.9556]])
tensor([[0.9761, 0.5934, 0.3124],
        [0.9431, 0.8519, 0.9815]])


tensor([[1.2494, 0.9331, 0.5003],
        [1.4965, 1.1200, 1.9371]])

In [ ]:
m.add_(n)
print(m)  ## Change in that variable and memory


tensor([[2.2255, 1.5265, 0.8127],
        [2.4397, 1.9719, 2.9186]])


In [ ]:
m

tensor([[2.2255, 1.5265, 0.8127],
        [2.4397, 1.9719, 2.9186]])

In [ ]:
n

tensor([[0.9761, 0.5934, 0.3124],
        [0.9431, 0.8519, 0.9815]])

In [ ]:
torch.relu(m)
m.relu_() ## _ performas the inplace operation for any function

tensor([[2.2255, 1.5265, 0.8127],
        [2.4397, 1.9719, 2.9186]])

## Copying Tensor

In [ ]:
x1 = torch.rand(2,3)

In [ ]:
x2 = x1

In [ ]:
id(x1)

140331356992080

In [ ]:
id(x2)

## Store in the same locaton by the assignment operation

140331356992080

In [ ]:
x3 = x1.clone()

In [ ]:
id(x3)

140331356459792

In [ ]:
id(x1)

140331356992080

## Tensors operation on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')
device

device(type='cuda')

In [ ]:
# Creating tensors on GPU
torch.rand(2,3,device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# Moving an existing tensor on GPU
a = torch.rand(2,3)
a.to(device)

tensor([[0.9952, 0.0015, 0.0813],
        [0.4907, 0.2130, 0.4603]], device='cuda:0')

## Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#
b = torch.rand(2,3,4)
b

tensor([[[0.3134, 0.2983, 0.3436, 0.2028],
         [0.9792, 0.4947, 0.3617, 0.9687],
         [0.0359, 0.3041, 0.9867, 0.1290]],

        [[0.6887, 0.1637, 0.0899, 0.3139],
         [0.1219, 0.3516, 0.2316, 0.2847],
         [0.3520, 0.2828, 0.2420, 0.4928]]])

In [ ]:
# Permute
b.permute(2,0,1)

tensor([[[0.3134, 0.9792, 0.0359],
         [0.6887, 0.1219, 0.3520]],

        [[0.2983, 0.4947, 0.3041],
         [0.1637, 0.3516, 0.2828]],

        [[0.3436, 0.3617, 0.9867],
         [0.0899, 0.2316, 0.2420]],

        [[0.2028, 0.9687, 0.1290],
         [0.3139, 0.2847, 0.4928]]])

In [ ]:
# unsquese
c = torch.rand(226,226,3)
# Image size
print(c.unsqueeze(dim=2).shape)
c.unsqueeze(dim=0).shape



torch.Size([226, 226, 1, 3])


torch.Size([1, 226, 226, 3])

In [ ]:
# Squeeze
d = torch.rand(1,20)
d.squeeze(dim=0).shape

torch.Size([20])

## Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
c = np.array([1,2,3])
torch.from_numpy(c)


tensor([1, 2, 3])