In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("breast-cancer.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
df.shape

(569, 32)

In [6]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [7]:
df.drop(columns=['id'],inplace=True)

In [8]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [9]:
x = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=42,test_size=0.20)

## Scaling

In [11]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [12]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

## Numpy array to pytorch Tensors

In [14]:
import torch

In [15]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
x_train_tensor.shape

torch.Size([455, 30])

## Defining the model 

In [17]:
class SimpleNN():
    def __init__(self,x):
        self.weights = torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
    
    def forward(self,x):
        z = torch.matmul(x,self.weights)+self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        espilon = 1e-7
        y_pred = torch.clamp(y_pred,espilon,1-espilon)

        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss


## Important Paramets

In [29]:
learning_rate = 0.1
epochs = 25


## Training pipeline

In [30]:
# Create model
model = SimpleNN(x_train_tensor)

# define a loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(x_train_tensor)
    # print(y_pred)
    

    # loss calculate
    loss = model.loss_function(y_pred,y_train_tensor)
    print(f'Epoch:{epoch+1},loss:{loss.item()}')
    
    # Backwards pass
    loss.backward()

    # Parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()


Epoch:1,loss:3.8170329565322842
Epoch:2,loss:3.692631991612619
Epoch:3,loss:3.564846281683778
Epoch:4,loss:3.4286968678253227
Epoch:5,loss:3.2870959290750292
Epoch:6,loss:3.137742530527495
Epoch:7,loss:2.98678549494479
Epoch:8,loss:2.8324959443162907
Epoch:9,loss:2.6707595446791594
Epoch:10,loss:2.5076892661452903
Epoch:11,loss:2.341495556017047
Epoch:12,loss:2.172169359869379
Epoch:13,loss:2.007571053943523
Epoch:14,loss:1.8445163381774456
Epoch:15,loss:1.684468633323887
Epoch:16,loss:1.5314644955665706
Epoch:17,loss:1.39115874665701
Epoch:18,loss:1.2657024075133132
Epoch:19,loss:1.1569431073371148
Epoch:20,loss:1.065772642878918
Epoch:21,loss:0.991721894428283
Epoch:22,loss:0.9330565987542099
Epoch:23,loss:0.887272153657734
Epoch:24,loss:0.8517860418364858
Epoch:25,loss:0.8243359881722048


In [31]:
model.weights


tensor([[ 0.2838],
        [-0.2817],
        [-0.3338],
        [-0.3126],
        [-0.0516],
        [-0.1121],
        [-0.0376],
        [-0.0442],
        [-0.2429],
        [-0.0790],
        [-0.1129],
        [ 0.5631],
        [-0.3905],
        [ 0.3312],
        [ 0.4248],
        [ 0.3386],
        [-0.2694],
        [ 0.1212],
        [ 0.1740],
        [-0.0098],
        [ 0.2420],
        [ 0.3600],
        [ 0.3467],
        [-0.3134],
        [ 0.2525],
        [ 0.3446],
        [ 0.2683],
        [-0.1663],
        [ 0.3007],
        [-0.0351]], dtype=torch.float64, requires_grad=True)

In [32]:
model.bias

tensor([-0.1461], dtype=torch.float64, requires_grad=True)

## Model Evulation

In [39]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred>0.7).float()
    accuaray = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy :{accuaray.item()}")
print(y_pred)


Accuracy :0.573253333568573
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
      