In [2]:
## NN module
## Torch.optim module



In [3]:
## Improvments 

# 1. building the neural network using nn module
# 2. Using built-in activation function
# 3. using built in loss function
# 4. Using built in optimizer




## One Node Model

In [4]:
# Create class model
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_featurs):
        super().__init__()
        self.linear = nn.Linear(num_featurs,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out



In [5]:
# create dataset
featurs = torch.rand(10,5)

# create a model
model = Model(featurs.shape[1])

# call the model forward pass
model(featurs)  # Starandard way to call the function  inseted of the model.features



tensor([[0.4542],
        [0.4174],
        [0.4234],
        [0.4444],
        [0.4297],
        [0.4458],
        [0.4430],
        [0.4463],
        [0.4521],
        [0.5622]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[-0.3043,  0.3329, -0.3066, -0.1614, -0.2427]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([0.1794], requires_grad=True)

In [8]:
from torchinfo import summary


summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Multi Node Layer

In [12]:
# Create class model
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_featurs):
        super().__init__()
        self.linear1 = nn.Linear(num_featurs,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out



In [13]:
# create dataset
featurs = torch.rand(10,5)

# create a model
model = Model(featurs.shape[1])

# call the model forward pass
model(featurs)  # Starandard way to call the function  inseted of the model.features



tensor([[0.4751],
        [0.4941],
        [0.4843],
        [0.4500],
        [0.4876],
        [0.4735],
        [0.4720],
        [0.4507],
        [0.4863],
        [0.4547]], grad_fn=<SigmoidBackward0>)

In [14]:
model.linear2.weight

Parameter containing:
tensor([[0.4353, 0.2910, 0.1427]], requires_grad=True)

In [15]:
model.linear1.weight

Parameter containing:
tensor([[-0.0449,  0.3886,  0.2196,  0.2761, -0.2222],
        [ 0.3005,  0.1531, -0.3551, -0.2548,  0.3917],
        [ 0.1726, -0.3714,  0.4274,  0.0523, -0.1234]], requires_grad=True)

In [17]:
## Sequential Container 

# Create class model
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_featurs):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_featurs,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
       

    def forward(self,features):
        out = self.network(features)
        return out



In [ ]:
# create dataset
featurs = torch.rand(10,5)

# create a model
model = Model(featurs.shape[1])

# call the model forward pass
model(featurs)  # Starandard way to call the function  inseted of the model.features



## With Dataset

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("breast-cancer.csv")

In [20]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [21]:
df.shape

(569, 32)

In [22]:
df.drop(columns=['id'],inplace=True)

In [23]:
x = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [26]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=42,test_size=0.20)

In [27]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [28]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [29]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [44]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [45]:
x_train_tensor.shape

torch.Size([455, 30])

In [46]:
class MysimpleNN(nn.Module):
    def __init__(self,num_featurs):
        super().__init__()
        self.linear = nn.Linear(num_featurs,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,featurs):
        out = self.linear(featurs)
        out = self.sigmoid(out)
        return out
    
    def loss_function(self,y_pred,y):
        espilon = 1e-7
        y_pred = torch.clamp(y_pred,espilon,1-espilon)

        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss


In [47]:
epochs = 25
learning_rate=0.1

In [48]:
# Create model
model = MysimpleNN(x_train_tensor.shape[1])

# define a loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model(x_train_tensor)
    # print(y_pred)
    

    # loss calculate
    loss = model.loss_function(y_pred,y_train_tensor)
    print(f'Epoch:{epoch+1},loss:{loss.item()}')
    
    # Backwards pass
    loss.backward()

    # Parameter update
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # Zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()


Epoch:1,loss:0.7563814520835876
Epoch:2,loss:0.734179675579071
Epoch:3,loss:0.7212622165679932
Epoch:4,loss:0.7135905027389526
Epoch:5,loss:0.7086774110794067
Epoch:6,loss:0.7051799893379211
Epoch:7,loss:0.7024220824241638
Epoch:8,loss:0.7000733613967896
Epoch:9,loss:0.6979728937149048
Epoch:10,loss:0.6960419416427612
Epoch:11,loss:0.6942403316497803
Epoch:12,loss:0.6925466656684875
Epoch:13,loss:0.6909481287002563
Epoch:14,loss:0.6894362568855286
Epoch:15,loss:0.6880050897598267
Epoch:16,loss:0.6866493821144104
Epoch:17,loss:0.685364842414856
Epoch:18,loss:0.6841471195220947
Epoch:19,loss:0.6829928159713745
Epoch:20,loss:0.681898295879364
Epoch:21,loss:0.6808604001998901
Epoch:22,loss:0.679875910282135
Epoch:23,loss:0.6789421439170837
Epoch:24,loss:0.6780561208724976
Epoch:25,loss:0.6772154569625854


In [50]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred>0.7).float()
    accuaray = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy :{accuaray.item()}")
print(y_pred)


Accuracy :0.6228070259094238
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
     

## Builtin Loss function

In [51]:
class MysimpleNN(nn.Module):
    def __init__(self,num_featurs):
        super().__init__()
        self.linear = nn.Linear(num_featurs,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,featurs):
        out = self.linear(featurs)
        out = self.sigmoid(out)
        return out

In [52]:
loss_function = nn.BCELoss()

In [60]:
# Create model
model = MysimpleNN(x_train_tensor.shape[1])

# define a loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(x_train_tensor)
    # print(y_pred)
    

    # loss calculate
    loss = loss_function(y_pred,y_train_tensor.view(-1,1))
    print(f'Epoch:{epoch+1},loss:{loss.item()}')
    
    # Backwards pass
    loss.backward()

    # Parameter update
    with torch.no_grad():
        model.linear.weight-= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # Zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()


Epoch:1,loss:1.2254136800765991
Epoch:2,loss:0.8206949830055237
Epoch:3,loss:0.5874050259590149
Epoch:4,loss:0.47077542543411255
Epoch:5,loss:0.405375599861145
Epoch:6,loss:0.3628891408443451
Epoch:7,loss:0.33257222175598145
Epoch:8,loss:0.30956435203552246
Epoch:9,loss:0.291331946849823
Epoch:10,loss:0.27641552686691284
Epoch:11,loss:0.26391035318374634
Epoch:12,loss:0.2532230317592621
Epoch:13,loss:0.24394680559635162
Epoch:14,loss:0.23579230904579163
Epoch:15,loss:0.22854764759540558
Epoch:16,loss:0.2220534086227417
Epoch:17,loss:0.21618708968162537
Epoch:18,loss:0.21085281670093536
Epoch:19,loss:0.20597420632839203
Epoch:20,loss:0.20148952305316925
Epoch:21,loss:0.19734834134578705
Epoch:22,loss:0.1935088336467743
Epoch:23,loss:0.18993602693080902
Epoch:24,loss:0.1866004914045334
Epoch:25,loss:0.18347707390785217


In [61]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred>0.7).float()
    accuaray = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy :{accuaray.item()}")
print(y_pred)


Accuracy :0.5409356951713562
tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
     

## Bulitin Optimizer

In [ ]:
## Define a optimizer
optimizer = torch.optim.SGD(model.w)

In [62]:
class MysimpleNN(nn.Module):
    def __init__(self,num_featurs):
        super().__init__()
        self.linear = nn.Linear(num_featurs,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,featurs):
        out = self.linear(featurs)
        out = self.sigmoid(out)
        return out

In [65]:
# Create model
model = MysimpleNN(x_train_tensor.shape[1])

## Define a optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

## Model.paramerer is iterator 

# define a loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(x_train_tensor)
    # print(y_pred)
    

    # loss calculate
    loss = loss_function(y_pred,y_train_tensor.view(-1,1))
    
    
    optimizer.zero_grad()
    # Backwards pass
    loss.backward()

    optimizer.step()
    print(f'Epoch:{epoch+1},loss:{loss.item()}')
    

Epoch:1,loss:0.7392122745513916
Epoch:2,loss:0.5631040334701538
Epoch:3,loss:0.4671401083469391
Epoch:4,loss:0.4082950949668884
Epoch:5,loss:0.36789393424987793
Epoch:6,loss:0.33800172805786133
Epoch:7,loss:0.3147428631782532
Epoch:8,loss:0.29598715901374817
Epoch:9,loss:0.2804553210735321
Epoch:10,loss:0.2673264741897583
Epoch:11,loss:0.25604602694511414
Epoch:12,loss:0.24622389674186707
Epoch:13,loss:0.23757632076740265
Epoch:14,loss:0.22989118099212646
Epoch:15,loss:0.22300618886947632
Epoch:16,loss:0.21679478883743286
Epoch:17,loss:0.2111564427614212
Epoch:18,loss:0.20601022243499756
Epoch:19,loss:0.20129020512104034
Epoch:20,loss:0.19694194197654724
Epoch:21,loss:0.19292010366916656
Epoch:22,loss:0.1891866773366928
Epoch:23,loss:0.1857094168663025
Epoch:24,loss:0.18246084451675415
Epoch:25,loss:0.17941734194755554


In [66]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred>0.7).float()
    accuaray = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy :{accuaray.item()}")
print(y_pred)


Accuracy :0.5430901646614075
tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
     