In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
x,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [4]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [6]:
x.shape

(10, 2)

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [9]:
x = torch.tensor(x,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)


C:\Users\Admin\AppData\Local\Temp\ipykernel_4012\2351802563.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x,dtype=torch.float32)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4012\2351802563.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y,dtype=torch.long)


In [14]:
from torch.utils.data import DataLoader,Dataset

In [17]:
class CustomDataset(Dataset):
    def __init__(self,featurs,labels):
        self.featurs = featurs
        self.labels = labels

    def __len__(self):
        return self.featurs.shape[0]
    
    def __getitem__(self, index):
        return self.featurs[index],self.labels[index]

In [19]:
dataset = CustomDataset(x,y)
dataset

In [20]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [21]:
for batch_featurs , batch_labels in dataloader:
    print(batch_featurs)
    print(batch_labels)
    print("---------------")

tensor([[ 1.7774,  1.5116],
        [-0.9382, -0.5430]])
tensor([1, 1])
---------------
tensor([[-0.7206, -0.9606],
        [ 1.0683, -0.9701]])
tensor([0, 1])
---------------
tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]])
tensor([0, 1])
---------------
tensor([[ 1.8997,  0.8344],
        [-1.1402, -0.8388]])
tensor([1, 0])
---------------
tensor([[-0.5872, -1.9717],
        [-2.8954,  1.9769]])
tensor([0, 0])
---------------


In [ ]:
# We can apply all the transormation above the getitem

## For the parralerly work
# dataloader have a worker classs
